version: "3"

services:
    my_zulip_dev:
        container_name: my_zulip_dev
        build:
            context: .
            dockerfile: Dockerfile
            args:
                - USER_NAME=alick
                - USER_GROUP=alick
                - USER_PASSWORD=1
                - UBUNTU_VERSION=18.04

        image: my_ubuntu_zulip:v1
        volumes:
            - data_volume:/home/alick
        ports:
            - "8022:22"
        network_mode: "bridge"
volumes:
    data_volume:
        external:
            name: my_ubuntu_workspace_data_volume
