version: '3'
services:
    mydb:
        container_name: mydb
        image: postgres:9.5
        volumes:
            - ./workspace/data/:/var/lib/postgresql/data/
        ports:
            - 15432:5432/tcp
        environment:
            POSTGRES_PASSWORD: postgres 
